[package]
name = "sequence-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sequence"
path = "main.rs"

[dependencies]
bubbletea-rs = { path = "../.." }
tokio = { version = "1.0", features = ["full"] }