[package]
name = "set-window-title-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "set-window-title"
path = "main.rs"

[dependencies]
bubbletea-rs = { path = "../.." }
lipgloss-extras = { version = "0.0.9", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }