[package]
name = "cellbuffer-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cellbuffer"
path = "main.rs"

[dependencies]
bubbletea-rs = { path = "../../" }
crossterm = "0.27"
tokio = { version = "1.25.0", features = ["full"] }
