[package]
name = "suspend-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "suspend"
path = "main.rs"

[dependencies]
bubbletea-rs = { path = "../.." }
crossterm = { version = "0.29.0", features = ["event-stream"] }
tokio = { version = "1.0", features = ["full"] }