[package]
name = "spinners-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "spinners"
path = "main.rs"

[dependencies]
bubbletea-rs = { path = "../.." }
crossterm = "0.29"
rand = "0.9.2"
tokio = { version = "1.0", features = ["full"] }
