[package]
name = "list-simple-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "list-simple"
path = "main.rs"

[dependencies]
bubbletea-rs = { path = "../.." }
crossterm = "0.27"
tokio = { version = "1.0", features = ["full"] }