[package]
name = "mouse-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mouse"
path = "main.rs"

[dependencies]
bubbletea-rs = { path = "../../" }
tokio = { version = "1.25.0", features = ["full"] }
crossterm = "0.29"