[package]
name = "composable-views"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "composable-views"
path = "main.rs"

[dependencies]
bubbletea-rs = { path = "../.." }
crossterm = "0.27"
tokio = { version = "1", features = ["full"] }