[package]
name = "exec-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "exec"
path = "main.rs"

[dependencies]
bubbletea-rs = { path = "../.." }
bubbletea-widgets = "0.1.9"
crossterm = "0.29"
tokio = { version = "1.0", features = ["full"] }